### PR TITLE
Adding Aeson

### PR DESCRIPTION
**Pull request by jonkri**
This pull request signals my work-in-progress of documentation for the Aeson package. I will ask for a review when I think it's ready.

### CODE REVIEW

**Comment by jonkri** [comment]
The aeson tutorial (found in the Haddocks) is really quite good, and there is a significant overlap between what I have written and that tutorial (I also borrowed the `Person` example from the Haddocks). However, I go through things in a slightly different order (from simple to complex) and explain the concepts in a (hopefully) more intuitive way for beginners. I of course also provide some runnable GHCi and Stack examples.

What do you think?

**Comment by chrisdone** [comment]
I'll review this today, thanks!

**Comment by chrisdone** [comment]
I like it. It has examples, and builds up from the simple case to the manual case.

(By the way, I wrote the Haddock tutorial for Aeson. 💃 )

**Comment by jonkri** [comment]
Thank you! :) Oh, haha, I didn't know that! :)

**Pull request merged**
