### PR TITLE
Winnowing book links down

### PR DESCRIPTION
**Pull request by bitemyapp**
I explain in pretty good detail why I do or do not recommend various resources. My book was already in the list so it's not about that.

http://bitemyapp.com/posts/2014-12-31-functional-education.html

Possibly contentious PR but I wasn't happy recommending resources known to be dysfunctional or out of date. Before our book was available the beginner book my coauthor and I recommended was Thompson's _Haskell: Craft of Functional Programming_.

### CODE REVIEW

**Comment by jwiegley** [comment]
I would like to request that this pull request be reverted.  It should not be the author of a book who decides whether other, competing materials, deserve to be mentioned on a site devoted to learners.

It is perfectly understandable that @bitemyapp believes his book is superior; otherwise, he wouldn't have expended the time and energy to write it.  And I laud his efforts to improve the educational landscape for a difficult language like Haskell.  However, dropping mention of other texts, written by well-known figures like the late Paul Hudak, should really not be for him to decide.

**Comment by snoyberg** [comment]
@jwiegley Thank you for pointing this out. The primary goal of this website is to get people trying out Haskell for the first time to have the easiest onboarding experience possible. The metric we're using for book recommendations is to avoid books that have historically generated a lot of confusion by new users. We're not trying to give a comprehensive list of all texts available.

We're basing these decisions off of first hand experience (read: anecdotal), not off of some hard data (like a survey of the community). If you have counter anecdotal experience, I'd be happy to hear it, I'm certainly open to hearing it. But for now, the books in this list are the ones we know haven't scared off new users too often.

Note that this isn't just about keeping Chris Allen's book and no others: in addition to two non-introductory books (Simon Marlow's and mine), there are two other books in that list (Simon Thompson's and Richard Bird's).

I'll take this time to say: the documentation page is on our list of things that needs to be improved on the website, and I think including some descriptions for the books is probably necessary at some point. Our main thrust until now has been earlier in the onboarding process (homepage and getting started). I'd be happy to hear more community ideas on improving the documentation page.

**Comment by jwiegley** [comment]
Thank you for that clarification, @snoyberg.  What you're doing with the page makes more sense to me now: you want to create an introductory list of "first materials", rather than a comprehensive list of what's available. I suppose feedback is indeed the best metric to determine what is helpful to newcomers, and what is "too much too soon".  In that light, I'll withdraw my request, and leave it to your judgement as to what you think best promotes the interests of those users.

Have you also given thought to what the transition experience will be like, after a user has gotten his feet wet and wants to engage more deeply in what's available?  I'm always torn myself between providing a clean minimum, but in a way that lets them conveniently explore more links if they find the interest, yet without creating a link forest that makes it too easy to get lost...

**Comment by dpwiz** [comment]
Perhaps a section clarifier would be helpful to avoid reactions like that in the future. Something along the lines of “the books in this list are the ones we know haven't scared off new users too often”.

**Comment by snoyberg** [comment]
Thanks for the feedback to both of you, I've just added a comment to #10 about giving such clarifying annotations, which I think is a great idea. I'd recommend if you have further ideas for documentation page improvements to put them there; it's too easy to lose useful feedback on a closed PR :)

**Pull request merged**
