### PR TITLE
Foreign package tutorials

### PR DESCRIPTION
**Pull request by snoyberg**

### CODE REVIEW

**Comment by chrisdone** [comment]
Nice!

**Comment by snoyberg** [comment]
Arguably the approach with a type variable is overkill, and just adding a new field for the optional URL is simpler. I'm open to that.

**Comment by chrisdone** [comment]
@snoyberg I'm not sure what the type variable is doing. What's the benefit?

**Comment by snoyberg** [comment]
We just replace the URL to the tutorial with the actual content, making it impossible to misuse (e.g., you can't accidentally use the original value with the hard-coded `Nothing` for content before checking the URL/local files).

**Comment by snoyberg** [comment]
Closing since #57 is merged.

**Pull request closed without merging**
